name: CI - Integracao Continua (Testes)

# Define quando a automacao sera executada
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    name: Executar Testes Unitarios
    runs-on: ubuntu-latest # Maquina virtual temporaria Linux do GitHub

    steps:
      - name: 1. Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar o ambiente Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 3. Instalar dependencias do projeto
        run: npm ci

      - name: 4. Executar os Testes Automatizados
        run: npm test